### ISSUE TITLE
accommodate multiple label translations

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#119]
Each label should have the ability to have up to 10 different template text translations. This might be a separate model so that translations can be added to the BCLabel model easily.

**Comment by birbjam** [comment]
Currently one translation is available, will add ability to add more in version 2

**Comment by nay-nay24** [comment]
Unsure if UI needed - will just be a repeating pattern?

**Comment by birbjam** [comment]
There already is UI for it, it just needs to be implemented.
