### ISSUE TITLE
Add tooltips to relevant pages

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/localcontexts_db#131]
We need a link, like "about this" after label approval to let the user know that they need another member to approve the label and then it can be used.

**Comment by birbjam** [comment]
Tooltip component created, just needs content

**Comment by birbjam** [comment]
Registration process tooltips added

**Comment by birbjam** [comment]
Create Project tooltips added

**Comment by birbjam** [comment]
This is done, we might just need to change some of the content later
