### ISSUE TITLE
Connect `Share Project` button in `view-project`

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#268]
Currently the button does nothing.
Need to find out what kind of sharing this will be... embedded link?

**Comment by birbjam** [comment]
btn that will copy public project to clipboard

**Comment by nay-nay24** [comment]
I have these ready in the design library

**Comment by nay-nay24** [comment]
Could we also align the back button to the left instead of the right? And then we can place the other buttons on the right :)

**Comment by birbjam** [comment]
Yes, I can definitely do that.
