### ISSUE TITLE
Adding project images & image carousel

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#292]
`Create Project`
- [ ] Add ability to add up to 5 images

`Edit Project`
- [ ] Add more images
- [ ] Be able to delete images

`View Project` 
- [ ] Show all images
 - [ ]  Image carousel when clicked on large image
 - [ ]  When clicked on small images, they replace the large image

**Comment by nay-nay24** [comment]
Will add this back into project form and project view
