### ISSUE TITLE
Add download function to project/Labels

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#311]
Need clarification on what exactly is going to be downloaded.
This will go into the meatball menu on Project Overview cards in `/projects`.

Assumption will be: 
1. `.txt` file with Label text
2. Label SVGs
3. Use instrutions
4. Readme

**Comment by birbjam** [comment]
Project information `.txt` text

**Comment by nay-nay24** [comment]
Will add this to 'project view' page and the drop-down on the project tiles

**Comment by birbjam** [comment]
Note to self on App Engine error with the PDF package:
https://stackoverflow.com/questions/63679134/modulenotfounderror-no-module-named-xhtml2pdf-under-google-app-engine

**Comment by birbjam** [comment]
This is mostly done.
Tasks to complete:
- [ ] Add Label Translations into `.txt` files for each Label
- [ ] Add dynamic `README.txt` with list of included file names and other helpful info
