### ISSUE TITLE
Project Additional Project People: be able to remove from `create-project` and `edit-project`

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#372]
Right now when a user creates or edits a project, project contributors and project people can only be added and project people can be changed. Need to set up functionality to be able to remove them from a project.

Create Project:
- [x] Remove project person

Edit Project:
- [x] Remove contributors
- [x] Remove project people

**Comment by nay-nay24** [comment]
Will review the existing chip and create a chip that easily allows the user to remove the contributors they add
