### ISSUE TITLE
User notifications: being able to turn off emails

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#379]

**Comment by nay-nay24** [comment]
Will review existing screen and see how I can evolve this for user notification settings

**Comment by birbjam** [comment]
To set this up, this would be per user and per account member.
This will exclude essential emails that are needed to set up account or update the user on important information.

Essential emails are + mailgun template names:
- Activate: `activate_profile`
- Welcome: `welcome`
- Updates to the Privacy Policy: `privacy_policy_updates`
- Updates to the Hub: `hub_updates`

There would be an option to opt out of all the non-essential emails and a list to check/uncheck each type of notification.
