### ISSUE TITLE
Connections page for Institutions and Communities

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#396]
Needs more discussion about what this page will be, possibly something like registry with contact information. 
Connection profile information and connection key contacts.

**Comment by birbjam** [comment]
Connection with dropdown that has list of projects, linked to the project itself by simple href.

**Comment by nay-nay24** [comment]
IDIA - would like to create a workflow for how this will function and relate to rest of the site (This will be a big piece we believe) Will add a 'Tshirt size' for this soon

**Comment by birbjam** [comment]
There will be some discussion between Maui and Jane about this workflow wise.

**Comment by birbjam** [comment]
11/15/21 meeting:
The Connections counter will keep track of how many unique communities have applied a Label to a researcher or institution project. For communities, it will keep track of how many unique institutions and researchers have had projects where Labels from this community were applied.

The Connections page will serve as a way to contact these organizations via contact name and email.
It will look like the Projects page, except it will list connections with their basic information and projects that are relevant to this particular connection.

Information will include: name of organization, description, contact name, contact email, list of projects that will be linked to the specific projects in the hub.

**Comment by birbjam** [comment]
Added connections counter to dev site

**Comment by birbjam** [comment]
Connection page added, just needs display of Projects for each connection where a Label was applied.
