### ISSUE TITLE
add-member modal: needs to stay open if form submission did not go through

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#422]
From Corrie's testing: 

- When adding a member who is on the Hub, the feedback text does not appear until you hit the “add member” button again, so:
  - Selecting someone who is already a member of the account, hit send invitation, and the modal closes and the page refreshes. 
  - When you hit Add Members again, it then shows This user is already a member of this institution.
  - Sending an invitation to anyone who is not already a member of the account, hit send invitation, modal closes and the page refreshes. Again if you hit Add Members again, it then shows the feedback text.
  - Same with inviting someone who has already been invited. “This user has already been invited to this institution” only pops up after hitting “add member” button after page refreshes.

**Comment by nay-nay24** [comment]
Something we should also look at is currently when you add a new person who isn't on the platform it takes you to a new page and then you have to go back into your profile and back to the account you were in - Can we use a modal to add new members not currently in the hub for an account? :)

**Comment by birbjam** [comment]
@nay-nay24 I'll open an issue for that, I think I can definitely do that
