### ISSUE TITLE
Move invite user to LC Hub to a modal

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#444]
Something we should also look at is currently when you add a new person who isn't on the platform it takes you to a new page and then you have to go back into your profile and back to the account you were in - Can we use a modal to add new members not currently in the hub for an account? :)

_Originally posted by @nay-nay24 in https://github.com/biocodellc/localcontexts_db/issues/422#issuecomment-1009544112_

**Comment by arojas1** [comment]
![image](https://github.com/biocodellc/localcontexts_db/assets/60452620/cd9ec038-c4bd-4918-9106-187ebaffc9f1)
- Moving content from "Invite the to LCHUB" into modal instead of new page.

**Comment by lc-hd** [comment]
I'm closing out this issue since it was resolved with the following PR's

https://github.com/biocodellc/localcontexts_db/pull/973
https://github.com/biocodellc/localcontexts_db/pull/975
