### ISSUE TITLE
Geospatial integration within Project and Community models [enhancement]

### ISSUE THREAD

**Issue by melkimble** [biocodellc/localcontexts_db#447]
The following could potentially eliminate the need to rely on native-land.ca boundaries by providing a mode through which communities can create their own boundaries at account creation (and modify them from within the account post-creation). It would require installing GeoDjango requirements, but would use the same database (Postgres; [setting-up](https://docs.djangoproject.com/en/4.0/ref/contrib/gis/tutorial/#setting-up)). The base image in cloudbuild.yaml would probably need to change, as well. We had to use `ubuntu:focal` instead of the python3 image to install gdal dependencies in our dockerfile. 

**Backend**
[communities/models.py#L20](https://github.com/biocodellc/localcontexts_db/blob/af2ac0e9de3332deecf144c48de6b75678a85e3f/communities/models.py#L20)
Change import `from django.db import models` to `from django.contrib.gis.db import models`
Add field `geom = models.MultiPolygonField()` to `class Community(models.Model)`

Repeat for `class Project(models.Model) ` at
[projects/models.py#L8](https://github.com/biocodellc/localcontexts_db/blob/af2ac0e9de3332deecf144c48de6b75678a85e3f/projects/models.py#L8)

If an api/serializer is added for Project or Community, use the import to `GeoFeatureModelSerializer` with `from rest_framework_gis.serializers import GeoFeatureModelSerializer` for Project and Community serializers and add `geo_field = 'geom'` under `class Meta`.

Use GeoDjango ORM to create method/view for querying spatial intersection of project polygon, e.g. all communities that intersect with a project: [GeoDjango Intersects](https://docs.djangoproject.com/en/4.0/ref/contrib/gis/geoquerysets/#intersects) - uses [ST_Intersect in PostGIS extension for Postgres](http://postgis.net/docs/ST_Intersects.html)

**Frontend**
Instead of using the native-land.ca API with a bounding box when "Send Requests" is initiated, enable the creation of a community boundary (spatial polygon/geom) when an Indigenous community account is created (which can be modified).

When a project is created, the project creator also creates a project boundary. 

When "Send Requests" is initiated, pre-populate list of communities with intersect list, but allow user to append list with additional communities via the dropdown (as it currently operates).

**Comment by jdeck88** [comment]
Thanks for the information Mel.  Curation of tribal boundary data by native lands is firmly in their mandate and not within the local contexts mandate.  So, while curating our own polygons would have the advantage of streamlining the community experience within our application, it could cause confusion and duplication of effort for tribes that have already entered their data in another application and better to apply our efforts towards integrating the two applications.  Let me know if you have further questions...

**Comment by melkimble** [comment]
Hi John - thank you for the quick response! That makes sense. Would that preclude projects having a `MultiPolygonField ` for their project boundary? A benefit of this would be providing maps with the project boundary to community accounts during a notice to help in providing an informed decision on labels. The downside is that it does not appear as though it can be used to query the native lands dataset, because native-lands.ca seems to only provide an [API to query by point](https://native-land.ca/resources/api-docs/#Maps).

If notices will be by the boundary data provided by the native lands dataset, when a community creates an account, will they indicate which tribal boundary is theirs, and will the identifier for the boundary subsequently be stored in the community account? It would be helpful for us to know how the notices will function with respect to linking the native lands boundaries to community accounts, and thus projects to communities through the medium of the native lands dataset. Thank you again and appreciate the information!

**Comment by jdeck88** [comment]
Specifying a native lands tribal boundary is optional for communities... so, when a community selects this optional field, our database will store the slug, which is native land's version of a persistent identifier for boundaries for each tribe.  Our application will use this information to help facilitate notifications between projects and communities.. kind of an alert system  notification.  

I've decided to keep the project boundary a simple bounding box because this is meant to be high level metadata and a way in which we can get a general sense of the project boundary.  A bounding box metadata field is common for other databases, e.g. GBIF, Geome, Vertnet and other biodiversity databases... And, easier to derive the simple point which can be passed to the native lands API.
