### ISSUE TITLE
Publicly Acccesible Hub UI page for Discoverable Projects

### ISSUE THREAD

**Issue by jdshaw** [biocodellc/localcontexts_db#458]
It would be great to have a publicly accessible page for **Discoverable** projects that includes the same data supplied by the API for Discoverable projects:

- unique id
- project name
- project labels & notices

The page would ideally also allow the user to log in and then, if they are a contributor to the project, be able to view the additional metadata for the project.

This would mirror the behavior exhibited by Public projects and bring the Hub UI into closer alignment with the API. Happy to supply more detail if need be.

**Comment by birbjam** [comment]
This is done
