### ISSUE TITLE
Spatial Footprint Field for Project Metadata

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/localcontexts_db#473]
Add a text field (must allow for up to 1Mb of text, so a long text field) to the Project Metadata structure called project_boundary_geojson.  In this field we store geojson like the following:  
```
{
	"type": "FeatureCollection",
	"features": [{
		"type": "Feature",
		"properties": {},
		"geometry": {
			"type": "Polygon",
			"coordinates": [
				[
					[
						-123.387451171875,
						44.18614312298759
					],
					[
						-123.44444274902344,
						44.125056482685146
					],
					[
						-123.387451171875,
						44.05601169578525
					],
					[
						-123.27484130859375,
						44.045154472558046
					],
					[
						-123.2508087158203,
						44.0693337495075
					],
					[
						-123.18969726562499,
						44.110267956688524
					],
					[
						-123.19107055664064,
						44.15708559147226
					],
					[
						-123.25767517089844,
						44.19943586247786
					],
					[
						-123.3050537109375,
						44.21617060273111
					],
					[
						-123.387451171875,
						44.18614312298759
					]
				]
			]
		}
	}]
}
```

When we insert the Geojson we probably need a way to validate (for structure only) before inserting into the database. E.g. see https://gis.stackexchange.com/questions/11204/geojson-geocouch-questions-from-a-newb  

For now, we store just the GeoJson.  This polygon can be used to (later) structure a request to native-lands API endpoint:

End point: 
https://native-land.ca/wp-json/nativeland/v1/api/index.php

Post body:
```
{
	"maps": "territories",
	"polygon_geojson": {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -123.387451171875,
              44.18614312298759
            ],
            [
              -123.44444274902344,
              44.125056482685146
            ],
            [
              -123.387451171875,
              44.05601169578525
            ],
            [
              -123.27484130859375,
              44.045154472558046
            ],
            [
              -123.2508087158203,
              44.0693337495075
            ],
            [
              -123.18969726562499,
              44.110267956688524
            ],
            [
              -123.19107055664064,
              44.15708559147226
            ],
            [
              -123.25767517089844,
              44.19943586247786
            ],
            [
              -123.3050537109375,
              44.21617060273111
            ],
            [
              -123.387451171875,
              44.18614312298759
            ]
          ]
        ]
      }
    }
  ]
}
}
```
This will return a response containing intersecting communities and their boundaries.... 

Create JSON file in localcontexts_json repo that lists the project name (using project_ID)  with an array of native-lands names (using their slugs) that intersect this project... This file will then be used on the project page itself to reference intersecting native land projects.  BONUS: indicate which of these communities are registered in the LC HUB itself.

**Comment by birbjam** [comment]
I'll look into it and see if Django has a GeoJSON field for their models.

**Comment by birbjam** [comment]
Done: JSONField added to Project model.

Next:
- Field needs to be added into create-project `views.py` and template.
- Also need to set up a way to validate the JSON structure.
