### ISSUE TITLE
Project: be able to add an external project id

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#488]
Add a field to the Project model that captures an external id.
(verbatim project id or provider's project id)

Set up the API to be able to query a Project by this ID.

**Comment by AaronWilton** [comment]
my handle

**Comment by jdeck88** [comment]
The solution to implement here:
Setup a filter on:
"https://localcontextshub.org/api/v1/projects/",
?providerProjectId=VALUE

this filter can also filter any project metadata value...
return is a filtered set of projects which normally come back from this service...

The user then grabs the project_unique_id from the resultset and sends request to the other services this way.

This approach helps us negotiate issues in global uniqueness and potentially problematic characters in the request string portion between the forward slashes (/) which is more sensitive to non-standard ascii characters.

**Comment by birbjam** [comment]
A `providers_id` can be added to a Local Contexts Project on creation, which can then be searched for in the API:
See: https://github.com/biocodellc/localcontexts_db/wiki/API-Documentation#project-list-filtering
