### ISSUE TITLE
Include ISO Language code(s) in API results

### ISSUE THREAD

**Issue by jdshaw** [biocodellc/localcontexts_db#501]
For accessibility purposes, it'd be great to have the iso 639 language codes added to the API results for both the initial language and any translations. That way the displayed text for the initial label language and any translations can be properly marked in reference to the parent page that is displaying the API data.

WCAG reference: https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html

May be related to #459 

Thanks!

**Comment by birbjam** [comment]
This is pretty much done, it will probably need a bit of refinement later.
