### ISSUE TITLE
Label Overview PDF not displaying macron letters

### ISSUE THREAD

**Issue by nay-nay24** [biocodellc/localcontexts_db#514]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/93554103/161885134-83232cd2-f57c-4883-8536-309f17aac703.png">

**Comment by birbjam** [comment]
Thanks Renee! I think this is due to when the PDF is written, it uses Arial instead of BC Sans. Will fix

**Comment by birbjam** [comment]
It looks like xhtml2pdf does not allow font imports so I can't change it to BC Sans. Not sure how to approach this.

**Comment by nay-nay24** [comment]
Hmmm - that's not good I am sure there is other descriptions that will use other characters

**Comment by birbjam** [comment]
<img width="1016" alt="Screen Shot 2022-07-07 at 11 43 12 AM" src="https://user-images.githubusercontent.com/41635757/177846289-4ad4ad88-7499-49db-a4f8-9ca3120706e4.png">

**Comment by birbjam** [comment]
I think the solution for this will simply be to keep information in .txt files and not have an overview PDF? Needs discussion.

**Comment by birbjam** [comment]
https://doc.courtbouillon.org/weasyprint/stable/index.html

**Comment by birbjam** [comment]
Was able to add BCSans in `.tff` format and this worked and is resolved. Pushing to test hub now, will update main hub today.
