### ISSUE TITLE
API does not provide community shared/placed labels

### ISSUE THREAD

**Issue by jdshaw** [biocodellc/localcontexts_db#589]
Not sure if this is a bug or a feature request, but for projects that have labels shared by a community (example: https://anth-ja77-lc-dev-42d5.uc.r.appspot.com/projects/5313177c-c1e8-4e69-b083-aa5e27e4b6e1/), the shared labels do not appear in the API data (https://anth-ja77-lc-dev-42d5.uc.r.appspot.com/api/v1/projects/5313177c-c1e8-4e69-b083-aa5e27e4b6e1/)

Should I expect to see those shared labels (ie its a bug?) or is am I requesting a new feature? If its a new feature, would be great to know if the data structure for the shared labels will be the same as for directly applied labels or if there will be some additional keys like 'shared_by': COMMUNITY_NAME in the api json.

Thanks!

**Comment by birbjam** [comment]
@jdshaw This is definitely not supposed to be happening, I will work on fixing it.

**Comment by birbjam** [comment]
@jdshaw This has been adjusted, Labels now showing in API.
