### ISSUE TITLE
Add option to API to call multiple Project IDs at once

### ISSUE THREAD

**Issue by arojas1** [biocodellc/localcontexts_db#594]
A few requests were put in to use one call to get the project details for multiple projects at once by passing multiple project IDs.

**Comment by birbjam** [comment]
@arojas1 Do you want to take this one on?

**Comment by birbjam** [comment]
Great, thanks for taking that on @arojas1 !
I'm thinking a user should be able to make calls with both `unique_id` and also `providers_id`.

**Comment by arojas1** [comment]
Of course @birbjam ! I was thinking the same thing. Though a few notes I can think of at the moment to think consider:

- Should there be a max number of ids that can be added?
- Should there be separate calls for `providers_id` and `unique_id`

**Comment by birbjam** [comment]
Let me get back to you on max number of IDs but yes two separate calls for the different IDs, I think.

**Comment by birbjam** [comment]
I think for now we can keep it as unique ids multi search until someone asks for providers id multi-search. I'm closing this.
