### ISSUE TITLE
Content updates for Registration > Choose an account

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#644]
Adding clarification to the “Choose an account” page in the registration process through text updates and adding a tooltip.

### Current text
<img width="1354" alt="Screenshot of the Choose an account page in the Hub" src="https://user-images.githubusercontent.com/49764220/193894514-30fe939a-d4f3-41aa-8a4d-4f915d61e9cc.png">

### Updated text

**Choose an account**
Local Contexts has three types of accounts. You can choose to join an existing account or create a new account. You can be a member of multiple accounts. 

**Community account**
_[Add tooltip]_ A community entity might be an Indigenous or local community Cultural Department, Tribal and Historical Preservation Officers, Community Center, Preservation Office, Community Library, Archive, Museum, or Land Council
Who? An Indigenous or local community entity or representative
What? Customize and apply Traditional Knowledge and Biocultural Labels, and create projects

**Institution account**
_[Tooltip]_ An institution might be an archive, library, museum, historical society, gallery, data repository, university, or media production company
Who? Cultural or research institution, data repository, and other organizations. If you are an Indigenous institution, choose the community account.
What? Create projects and generate Notices

**Researcher account**
Who? An individual who carries out academic or scientific research independently or in an institution
What? Create projects and generate Notices

**Comment by birbjam** [comment]
Under community account, can I shorten 
> What? Customize and apply Traditional Knowledge and Biocultural Labels, and create projects

to just say TK and BC Labels?
The length of it interferes with the styling.

![Screen Shot 2022-10-04 at 3 34 55 PM](https://user-images.githubusercontent.com/41635757/193942516-673110c0-211d-4108-87c6-abaacbcf98d7.png)

VS

![Screen Shot 2022-10-04 at 3 35 23 PM](https://user-images.githubusercontent.com/41635757/193942572-76998b04-1e4c-4164-8593-73b710ef7550.png)

**Comment by birbjam** [comment]
@corrieroe 
Also kind of an issue with the Institution content

![Screen Shot 2022-10-04 at 3 38 14 PM](https://user-images.githubusercontent.com/41635757/193943500-ab501f1d-1f90-4c00-9b73-9221c7fbf10f.png)

**Comment by corrieroe** [comment]
@birbjam makes sense! Both those edits look good to me.
