### ISSUE TITLE
Content update for Project overviews > Notify Communities

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#647]
The "Notify Communities" content on the project overview for institution and researcher accounts should include all the statuses.

### Current text in researcher/institution account
<img width="1386" alt="Screen Shot 2022-10-04 at 2 30 32 PM" src="https://user-images.githubusercontent.com/49764220/193899740-3614ccc7-d903-4870-a7a3-05c7e61b0f21.png">

### Updated text
**Notify Communities**
Listed below are the communities you have notified about this project. After the name of the notified community is the status of their decision about the Project. The status options are:
_Acknowledge Notice:_ The Project has been seen, but the community has not made a decision about applying Labels.
_No Labels Pending:_ The community will not apply Labels to the Project.
_Labels Pending:_ The community is deciding which Label(s) to apply to the Project.
_Labels Applied:_ The community has applied Labels to the Project.

**Notified Communities and Label Status**
..........

**Comment by birbjam** [comment]
@corrieroe 
So a community would see

> Acknowledge Notice: The Project has been seen, but the community has not made a decision about applying Labels.

But on the institution / researcher side it would just change this status from _Sent_ to _Seen_

![Screen Shot 2022-10-04 at 3 56 18 PM](https://user-images.githubusercontent.com/41635757/193945633-78211364-9ad9-417c-8790-5ea2bce07cda.png)

So the acknowledge notice part will just be on the community account

![Screen Shot 2022-10-04 at 3 59 14 PM](https://user-images.githubusercontent.com/41635757/193945819-0fdfffad-ceb8-4c8a-8da3-bada1389e04e.png)

**Comment by corrieroe** [comment]
Ah got it! Does it make sense to add "Sent" and/or "Seen" to the list in institution/researcher accounts?

**Comment by birbjam** [comment]
@corrieroe I feel like those are pretty self-explanatory and don't necessarily need to be explicitly stated. What do you think?

Also, should the content be updated for communities as well? The wording is a bit different.

**Comment by corrieroe** [comment]
Sorry I wanted to make sure I understood the statuses, how they change, and where they appear, just checked it out... 

So my understanding is the status changes from Sent to Seen after a community member selects "acknowledge notice," it's not an automatic status change (for example, it doesn't change when a member views their notification about the project). 

I think it will be helpful to include "Seen" in the list. It is pretty self-explanatory, but I think it will make it extra clear about what is going on with the project, what an institution/researcher can expect next. So it could be:

> Seen: The community has acknowledged the project but has not made a decision about applying Labels.

I think it would be great to update the wording for communities to match this. So under Project Decision it should be:

You can share a status update about this project by selecting from these options:
_Acknowledge Notice:_ You have seen the Project but have not made a decision about applying Labels.
_Labels Pending:_ You are deciding which Label(s) to apply to the Project.
_No Labels Pending:_ You will not apply Labels to the Project.
_Labels Applied:_ This will automatically be your status if you have applied Labels to the Project.
