### ISSUE TITLE
Content update for Registration > Verify your email

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#650]
Clarify and add in time limit on the Verify your email page during registration.

### Current text
<img width="1032" alt="Screen Shot 2022-10-04 at 2 52 06 PM" src="https://user-images.githubusercontent.com/49764220/193902039-391afad6-8f8c-4bf5-8d32-4bcb66900819.png">

### Updated text (bold and bullets as below, if possible)
**A verification link has been sent to the email you provided.** 

- Your email must be verified within 30 days in order to be activated.
- If you have verified your email, you’re all set! You can close this window.

**Didn’t get an email?**

- Check your spam or junk folder for an email from no-reply@localcontextshub.org
- If you do not receive an email within 5 minutes, please enter your email below to send it again. If you have not received an email after this, please contact us.

**Comment by birbjam** [comment]
Updated in test hub, will update in main Thursday 10/06
