### ISSUE TITLE
Feature Request: Add Label/Notice links to API response

### ISSUE THREAD

**Issue by jdshaw** [biocodellc/localcontexts_db#664]
It would be useful to have a direct link to the individual Labels/Notices in the API response for a project. I'm thinking something like an additional uri in each Label or Notice object. I think this would also necessitate adding a public/not public status for individual Labels and Notices and allow for direct linking to the Label or Notice for non-authenticated/non-authorized users if the status is public.

Use case: 

For the integration with ArchivesSpace, I'd like to be able to provide an updated MARC XML export (one of the core ArchivesSpace exports). MARC XML is used in standard cataloging systems like those provided by OCLC or Ex Libris. 

The various Labels and Notices tend to map to 5xx fields (https://www.loc.gov/marc/bibliographic/bd5xx.html), and those fields allow for an optional $u subfield that links off to an external resource that more fully describes the contents of that field. That would allow us to keep the label text and images together as is best practice.

Example 506 field for a Seasonal Label

506  ##$aThis Label is being used to indicate that this material traditionally and usually is heard and/or utilized at a particular time of year and in response to specific seasonal changes and conditions. For instance, many important ceremonies are held at very specific times of the year. This Label is being used to indicate sophisticated relationships between land and knowledge creation. It is also being used to highlight the relationships between recorded material and the specific contexts where it derives, especially the interconnected and embodied teachings that it conveys. This Label is being used to indicate that this material traditionally and usually is heard and/or utilized at a particular time of year and in response to specific seasonal changes and conditions. For instance, many important ceremonies are held at very specific times of the year. This Label is being used to indicate sophisticated relationships between land and knowledge creation. It is also being used to highlight the relationships between recorded material and the specific contexts where it derives, especially the interconnected and embodied teachings that it conveys. More information about this Label:$u[URI_TO_LABEL]

**Comment by birbjam** [comment]
@jdshaw thanks for opening this issue!

We did make the decision to not have individual community customized Labels be accessible via API because we wouldn't want people to just use those calls and put Labels on things that communities are either not aware of or did not agree to but I'll check in with the team on Monday and see what the consensus is.

**Comment by jdshaw** [comment]
@birbjam Totally understand how this could open up the Labels and Notices for potential misuse. I hadn;t considered that aspect of things, so since this is a *very* niche use case, and MARC XML is extremely rigid in its application, if there's any concern about the misuse, I'd prefer to keep things as is and look for alternative solutions for the MARC export. 

I'm going to continue researching the options to see if there's a MARC field that would allow linking to the entire project - which would be the best solution. I'm got some questions in to our local experts and will keep you posted.

**Comment by birbjam** [comment]
@jdshaw That sounds good, let me know what solution ends up working for you. I checked in with the team and there was consensus on not having individual Label calls to prevent misuse. Closing issue for now.
