### ISSUE TITLE
Registry search bar - search across account types?

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#698]
Related to [655](https://github.com/biocodellc/localcontexts_db/issues/655)

Would it be possible to search across account types with the registry search bar? As it is currently, you need to be "browsing" the account type in order to show the results within that account type, for ex., if you search for "academy" when browsing community or researcher accounts, there will be no results, but if you search for "academy" when browsing institution accounts, there will be 1 result (screenshot below).

<img width="1508" alt="Registry search" src="https://user-images.githubusercontent.com/49764220/201703076-745103cc-e845-47f2-bed0-0fcc70430d73.png">

**Comment by birbjam** [comment]
@corrieroe I will look into it!

**Comment by birbjam** [comment]
Done, will update in the main hub.
