### ISSUE TITLE
Notify Communities - communities listed twice

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#706]
This was on someone else's view. On the dialogue page to Notify Communities, each community was listed twice in the dropdown list. I will try to find out more details about this, I cannot seem to replicate it.

<img width="1138" alt="Notify Communities - double community" src="https://user-images.githubusercontent.com/49764220/204592273-07a52caa-2221-4ab8-bcb0-47acc6deb937.png">

**Comment by birbjam** [comment]
Is this in test hub or main hub?

**Comment by corrieroe** [comment]
Sorry, test Hub.

**Comment by birbjam** [comment]
I saw the banner and realized where that was. Do you happen to know when this happened?

**Comment by corrieroe** [comment]
8:53 am today; it was on a project that already had Labels applied and she clicked Notify Communities

**Comment by birbjam** [comment]
Ok thanks I'll take a look

**Comment by birbjam** [comment]
Can't seem to reproduce this and with the new project action page setup this should no longer be happening anyway.
