### ISSUE TITLE
Notification for notified communities upon project edit

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#712]
Would it be possible to push a notification to communities that have been notified about changes made to a project? A notification is pushed out to project contributors, but a community is not considered a contributor until (if) they decide to apply Labels. 

Example (just did in test Hub, if helpful to look):
1. Researcher Corrie Roe creates project 'Research about Collection [test]' with a TK Notice.
2. Researcher Corrie notifies community account "Corrie Community" about the project.
3. Admin of the community account receives an email and notification that the project has been shared. In this case, I selected to update the status to "acknowledge."
4. Researcher edits the project. Email and notification that the project has been edited is pushed out only to the researcher. The community that received the project did not receive a notification/email because they are not a contributor.

**Comment by birbjam** [comment]
Can do, I think that's a good idea.

**Comment by birbjam** [comment]
I can make in-hub notifications for these but need clarification on who gets the emails in the notified community? Is it just the admins, or all member types?

**Comment by corrieroe** [comment]
I would say Admins at the least, but a question for the group I think

**Comment by birbjam** [comment]
Dev note: This email is being sent by the `send_contributor_email` function in `emails.py`. 
This whole function needs to be re-written because right now if you are the only contributor to a Project you will get an email if you make edits to it and this is not very helpful.
