### ISSUE TITLE
When community adds Label to Project, add to public page

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#725]
If a community decides to add Label(s) to a public Project from an institution / researcher, could it be added to their public page? 

So in addition to public Projects the community created, a community's public account page would also include links to the Projects that the community has applied Labels to. 

I do not think we should do this whenever an account is added as a contributor, only when a community decides to apply their Labels to a project they have been notified about.

**Comment by birbjam** [comment]
This is done and will appear in the main hub when the new project design is updated.
