### ISSUE TITLE
Record of activity around a Project

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#727]
Need to set up a way to record all the activity that takes place around a Project to be shown on the Project action page on the bottom.
- Project created by Name
- Project edited Date by Name
- Community applied the following Labels
Etc.

Current Figma for this:

<img width="587" alt="Screen Shot 2022-12-20 at 11 46 27 AM" src="https://user-images.githubusercontent.com/41635757/208753521-8906d806-5e6d-4819-a4f5-5d864d113ce1.png">

**Comment by corrieroe** [comment]
This is great to see 🤩  I can see people being interested in the dates associated with all the activities (in addition to when created), if such a thing was possible!

**Comment by birbjam** [comment]
This is done in test hub, will be added to main hub in January 2023
