### ISSUE TITLE
Edit Project: Content update

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#731]
When user goes to edit a project the content is from the Create Project page and needs to be adjusted.
<img width="1305" alt="Screen Shot 2022-12-21 at 2 46 10 PM" src="https://user-images.githubusercontent.com/41635757/209017175-750e14af-cac3-4376-a900-9e6e72a0e047.png">

**Comment by corrieroe** [comment]
I am not sure if this is 100% accurate, apologies
_____________________
**Projects** >> Edit a Project
### Edit a Local Contexts Project
A project describes the context where a Notice or Label is being applied. Project creators and contributors can edit a Local Contexts Project until Labels are applied. Project contributors will receive a notification that the Project has been edited.
