### ISSUE TITLE
Minor content/UI questions for new Project design

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#737]
These are small but I think could help the user experience! Lmk if screenshots would help for any not included. May add others / open new issue.

1. On the Projects tab and in the 'apply Labels' view, could the **Project titles be in the teal color** we use for links? I think people may not know they can click on the titles. I think it's still helpful to show the underline when hovering.
2. Anywhere we put the date (project activity, project messages, community notes), could we **specify the time zone**? I believe it's UTC? I don't think we need to specify the time if that is too much information, but to at least specify the time zone, somewhere small. We saw confusion come up during beta testing when a date was not what the user expected for their time zone.
3. On a Project page, possible to add a **help hint on the Archive button**? Something like (if this is accurate): "Projects that are archived will only appear in your archived project list. Projects can be unarchived at any time."
4. For community notes, knowing this may change in appearance/placement, but we may want to think about **specifying the user** who adds a note, instead of the community name (i.e. Corrie Roe instead of Southwest Community) Similar to what is done with the project messages.
5. Project actions page: Could the **title styles and line styles between sections be consistent** (unless there is a reason for them not to be)? Screenshot below.

_Screenshot: Project actions styling_
<img width="960" alt="Project activity sections" src="https://user-images.githubusercontent.com/49764220/214340992-37ed383a-8b8c-4380-8907-3108a1a3d76d.png">

**Comment by birbjam** [comment]
Everything except 2 has been adjusted / fixed. Updating test hub now.
