### ISSUE TITLE
Project activity - editing Labels

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#738]
When a Label is either removed or added, the Project activity says all the Labels were removed. If any Labels remain on the Project, they are then listed as applied again. I am wondering if it's possible to simplify the text so it is easier to understand which Labels were applied at any one time. 

_TK V, O, and A initially applied. Removing TK O._
<img width="977" alt="Project activity - removing Label" src="https://user-images.githubusercontent.com/49764220/214343675-f3b7acbd-94e3-4c9d-abb8-bffd73eeaf42.png">

_Same project, but adding TK O back._
<img width="975" alt="Project activity - Label added" src="https://user-images.githubusercontent.com/49764220/214344201-a484894e-40c8-4aba-9134-0913652dcd16.png">

Realizing it works differently with Notices, and there are fewer of them, but is it possible to do something similar to how adding / removing Notices is shown in the Project activity?

_Project created with TK Notice, edited and BC Notice added, edited and TK Notice removed._
<img width="965" alt="Project activity - Notices" src="https://user-images.githubusercontent.com/49764220/214347129-88dcb9e1-71f2-49a3-a0f5-e47ce5f5aa27.png">

If not possible, could all of the Labels applied be combined into one line? Imagine gets tricky with grammar. For the example above, with a Project 1) TK V, A, and O applied, 2) TK O removed, so TK V and A remain, 3) TK O added, so TK V, A, and O applied:

* TK Verified (TK V), TK Attribution (TK A), and TK Outreach (TK O) Labels applied by Southwest Community
* TK Verified (TK V) and TK Attribution (TK A) applied by Southwest Community
* TK Verified (TK V), TK Attribution (TK A), and TK Outreach (TK O) Labels applied by Southwest Community

**Comment by birbjam** [comment]
This has been fixed, updating the test hub now
