### ISSUE TITLE
Specify time zone for anywhere time is displayed

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#739]
> Anywhere we put the date (project activity, project messages, community notes), could we specify the time zone? I believe it's UTC? I don't think we need to specify the time if that is too much information, but to at least specify the time zone, somewhere small. We saw confusion come up during beta testing when a date was not what the user expected for their time zone.

(from #737)

**Comment by arojas1** [comment]
For now, add UTC. Continue to research to show date/time based on user's location.
