### ISSUE TITLE
Share and download on non-public projects

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#742]
When a Project is set to 'contributor view' or 'private,' the 'share' and 'download' options disappear from the Actions card. I think we would want to keep these buttons - I think we would want the Download to be functional on any visibility level. I think we might like the Share button to still be an option on contributor view also (if not for private projects also). If we only want the share button to be an option on public projects, could it remain but be grayed out (as we do with the 'delete' button after Labels have been applied)? 
<img width="1421" alt="Non-public project actions card" src="https://user-images.githubusercontent.com/49764220/215114689-74586e85-e91a-40d2-9a01-0dc57d17a6eb.png">

**Comment by birbjam** [comment]
Will add the option to archive.

- What will be downloaded with the contributor view?
Currently, Project download includes all information and its Notices / Labels in a zip file.

I think I also need to revisit who can see what in a contributor Project. 
1. Any contributor to the Project can see the whole thing (basically a whole Project Actions page)?
2. Anyone not involved (or unregistered users) only see Title, Unique ID and any Labels or Notices applied?

**Comment by corrieroe** [comment]
Adding clarification: When a Project creator views this page of a contributor view or private project, the "share" and "download" buttons do disappear from the actions option.

I think the other part of my question, about if these actions are available to others and on which project visibility, may require a spreadsheet to go through all possible combinations. This may also be covered as part of our conversations about what is visible for whom on a "contributor" project.

**Comment by birbjam** [comment]
Right now contributor view has three possible views:

1. Action Page, which is visible to any contributing account and all their members.
![screencapture-localhost-8000-researchers-projects-actions-1-5c27e235-0d0a-40c2-a40b-b5a3c4322fa2-2023-01-31-13_36_39](https://user-images.githubusercontent.com/41635757/215889118-903402d2-4acb-4aec-9e78-904038f2ab9d.png)

2. Public Project page (the shareable link), which is visible to contributors.
![contrib view](https://user-images.githubusercontent.com/41635757/215889513-4c0309a4-ae7a-4dc8-9a6e-fd3393f1b0da.png)

3. Public Project page (the shareable link), which is visible to non-contributors and unauthenticated users.
![Screenshot 2023-01-31 at 1 21 52 PM](https://user-images.githubusercontent.com/41635757/215889683-96b06bac-05b9-4a55-be9a-6d6d031e92bf.png)


I was thinking that for the second view (in both Public and Contributor Projects), under Actions there could be a 'View as:...' option where you can choose to view it as a certain account that is a contributor to the Project that the user is a part of. 
So for this example the, the account that created the Project is First Name Last Name researcher, so the option would be 'View as... First Name Last Name' and then it will take you to the 1st view (the Project Action page).
I think this would simplify jumping back and forth between these pages.
