### ISSUE TITLE
Project activity - edits after Labels

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#743]
After a Project is edited that currently has Labels applied (but originally had Notices), the Project activity says Notices were removed - this could be confusing, since the editor did not remove the Notices but only edited the project. 
<img width="1553" alt="Project activity - edit post-Labels" src="https://user-images.githubusercontent.com/49764220/215115844-57e5380f-55ae-4700-a526-0175bf212d77.png">

Wondering if we might want to include an additional activity as "Notices were replaced by Labels" when Labels are initially applied.

**Comment by birbjam** [comment]
Ok should be working properly now
