### ISSUE TITLE
Notify Communities: popup content update

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#745]
<img width="1318" alt="Screenshot 2023-01-27 at 3 05 36 PM" src="https://user-images.githubusercontent.com/41635757/215222529-40d2ff19-4c92-4fca-a87c-3e03ca3398bf.png">

This popup mentions the requests section which no longer exists in this new design, content needs to be altered.

**Comment by birbjam** [comment]
For now, updated to:
<img width="1322" alt="Screenshot 2023-02-01 at 12 45 04 PM" src="https://user-images.githubusercontent.com/41635757/216159348-324c501f-8ec9-4da8-9484-0625a15d07ff.png">

**Comment by birbjam** [comment]
For now, edited the content to this:
<img width="1322" alt="Screenshot 2023-02-01 at 12 47 08 PM" src="https://user-images.githubusercontent.com/41635757/216159677-74dabe95-0789-4b57-a05b-9f13494f3d57.png">

**Comment by corrieroe** [comment]
**Current text:**
By notifying relevant communities, they will be able to see this Project and decide whether or not they would like to add their Labels. After your organization has entered the communities you would like to to send these notifications to, you can monitor their statuses in the Communities Notified section that will appear under Project Actions.

Select a community/communities you'd like to notify of this Project*
_[Q: Is the asterisk to mark this as a required field?]_

Add a Project comment

**Update text to:**
Notify relevant communities about this Project to add them as a potential contributor. Notified communities can decide if they would like to add their Labels to the Project. Notified communities will also be able to see and edit Project details, see and add Project comments, and see Project activity. 

Select community/communities to notify about this Project

Add a Project comment
_[May still be worth discussing if this is a necessary field with this action]_

**Comment by birbjam** [comment]
<img width="721" alt="Screenshot 2023-02-22 at 2 13 54 PM" src="https://user-images.githubusercontent.com/41635757/220771947-02838844-a826-410d-885e-dcfe939018ed.png">
