### ISSUE TITLE
Label text info disclaimers (per privacy policy)

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#746]
Need some content to add disclaimers about adding any personal information into Project messages and Label text at Label customization.

**Comment by corrieroe** [comment]
I can make a suggestion of content for this! On my to-do

**Comment by corrieroe** [comment]
Think we can use basically the same language as in #744 , maybe add as a help hint on the customize Label page, next to "Label text"? We may want to consider adding the guidance about *why* someone might include personal information (such as an email) in our support materials, but not sure we need it here.

> Providing personal information is optional. By providing it, you consent for it to be shown to other Hub users and wherever this Label is applied. [Privacy Policy]


<img width="1423" alt="Screen Shot 2023-02-22 at 2 01 06 PM" src="https://user-images.githubusercontent.com/49764220/220732112-eed1a340-7f11-417c-b88c-9dc6931959ea.png">

**Comment by birbjam** [comment]
<img width="1358" alt="Screenshot 2023-02-22 at 11 12 47 AM" src="https://user-images.githubusercontent.com/41635757/220734684-c47c5b56-f644-41f4-b45c-1081264a6f02.png">
