### ISSUE TITLE
Update "discoverable" to "contributor view"

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#750]
Sometimes "discoverable" is used when we are currently calling that visibility "contributor view"

1. On projects tab, in the project list (on both created and contributed projects)

<img width="1420" alt="Discoverable in project list" src="https://user-images.githubusercontent.com/49764220/215863704-a4fbad4d-04d9-4240-874d-03b9e037d08b.png">

2. In top section of the view project page
<img width="958" alt="Discoverable in project page" src="https://user-images.githubusercontent.com/49764220/215863897-c4edb4b4-768a-44f6-91f8-3dd79c3127fd.png">

I think that's the only places I've seen it so far

**Comment by birbjam** [comment]
Updated in test hub
