### ISSUE TITLE
Project page: Communities notified idea/edits

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#756]
Would it be possible to have the Communities Notified section present on projects created in institution/researcher accounts, even if communities have not been notified? This might be a nice reminder for institutions/researchers to share the project. 

So instead of the Communities Notified appearing only after communities have been notified, this section is already under the Actions section, but empty. This would not be necessary for Projects created by community accounts.

**Fast mock-up**

![notify community](https://user-images.githubusercontent.com/49764220/217005220-6c8087d4-b5ee-425d-b334-5a77aebbc263.png)

**Content**
I know we have been talking about this, but not sure where we landed - would be good to streamline the content here. We may not need the text in the box if we are keeping the help hint, since it repeats the same information. The text in the "notify communities" pop-up is also helpful to explaining some of this. 

Current content
<img width="428" alt="Screen Shot 2023-02-06 at 9 46 43 AM" src="https://user-images.githubusercontent.com/49764220/217005565-ebabeb1a-54ef-4b7d-9b33-a0cdafe15848.png">

Current help hint
<img width="428" alt="Screen Shot 2023-02-06 at 9 49 54 AM" src="https://user-images.githubusercontent.com/49764220/217005587-a24a7bbe-e6d3-44d1-b169-9f5b9dfa5ab1.png">

**Comment by birbjam** [comment]
Done!

<img width="383" alt="Screenshot 2023-02-17 at 2 50 35 PM" src="https://user-images.githubusercontent.com/41635757/219812182-367e77d9-9082-4482-81ce-6ab32f579e5f.png">
<img width="440" alt="Screenshot 2023-02-17 at 2 50 58 PM" src="https://user-images.githubusercontent.com/41635757/219812212-8038553a-f66b-4d12-81d4-155ee8d5bb3e.png">
