### ISSUE TITLE
Small content - join accounts, notify communities

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#768]
1. Content for requests to join accounts
Related to #729 
Can we add small text to the left of the "send request" button?
"By sending this request, you consent for your message and email address to be shared with account administrators."

<img width="753" alt="Screen Shot 2023-02-22 at 2 10 43 PM" src="https://user-images.githubusercontent.com/49764220/220734130-3347ba2d-867c-4add-9b0e-7a457eca6d67.png">

2. Community needs to be notified to add Labels
When a community is added as a contributor but not notified, "Apply Labels" button is grayed out. 

"Your community was added as a contributor to this Project. The Project creator needs to notify your community if you wish to apply Labels. Please contact us with any questions."

<img width="1358" alt="Screenshot 2023-02-21 at 3 25 39 PM" src="https://user-images.githubusercontent.com/49764220/220742876-ea2f0f60-9720-4700-85f2-415e64cd32e5.png">

**Comment by birbjam** [comment]
Done, thanks Corrie!
<img width="750" alt="Screenshot 2023-02-22 at 1 58 08 PM" src="https://user-images.githubusercontent.com/41635757/220769004-56487530-9713-481c-b4f8-3a84158e1d20.png">
<img width="396" alt="Screenshot 2023-02-22 at 1 59 59 PM" src="https://user-images.githubusercontent.com/41635757/220769387-3b80fc26-c3a4-4c9a-a844-576fc586bd1c.png">
