### ISSUE TITLE
Embed Option for Notices/Labels

### ISSUE THREAD

**Issue by arojas1** [biocodellc/localcontexts_db#793]
Thinking about having an embed option for the Hub similar to how [Twitter](https://publish.twitter.com/#) generates embed code for timelines.

- [ ] Page on Hub that asks for Project ID (same how Twitter asks for username)
- [ ] Embed option with share button on Project view page that generates the code without needing to add the ID (youtube embed code generator)
- [ ] Embed code, when added to the webpage, will show Notice or Labels in a row
- [ ] Options for embed code including adding the Notice or Label text next to the icon or as a popup?
- [ ] Include a by-line that has the Project Name and a link to the Project view page

**Comment by birbjam** [comment]
This is done and in the test hub.
