### ISSUE TITLE
Responsive Hub page content

### ISSUE THREAD

**Issue by arojas1** [biocodellc/localcontexts_db#795]
Need to work on responsive content for the Hub pages. Content doesn't end up resizing based on window size.
![image](https://user-images.githubusercontent.com/60452620/228953903-cf6182f6-c190-4b40-9dfc-786496affad1.png)

**Comment by birbjam** [comment]
Chatted with Renee about this, she will work on the design for responsiveness after some of our bigger features including subscribers.
