### ISSUE TITLE
Related projects - Connect modal content / UI

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#800]
### Update the text in the modal:
**Currently:** Connecting related Projects enables better access to other Projects that have similar data.
**Update to:** Connect this Project to others in your account that are similar or have a relation.

### Small UI adjustment
It looks like the UI for the Projects in the modal is cut off at the bottom of the list (and maybe to the right side) - see screenshots for this across multiple modals with different sized lists.
<img width="806" alt="Connect project modal 1" src="https://user-images.githubusercontent.com/49764220/229816405-60ca35b1-dc93-485f-898f-2d15c66eee60.png">
<img width="793" alt="Connect project modal 2" src="https://user-images.githubusercontent.com/49764220/229816406-8fb93b10-9b31-43cf-85a6-e386b515c462.png">
<img width="791" alt="Connect project modal 3" src="https://user-images.githubusercontent.com/49764220/229816407-16d0541c-04eb-4f78-9e7f-84aa4b24427d.png">

**Comment by birbjam** [comment]
@corrieroe which browser is this?

**Comment by corrieroe** [comment]
@birbjam - Chrome, Version 111.0.5563.146 (Official Build) (arm64)
