### ISSUE TITLE
Related Projects - Private Projects

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#801]
### Creating or connecting a private Project enables others to see that Project (see video recordings for these steps)
**1. Project A is created by a researcher. An institution is added as a contributor. (Researcher is not a member in the institution account) [this is also throwing a 500 error]**

https://user-images.githubusercontent.com/49764220/229820058-a3a19634-1303-459b-b1d6-4eab13674752.mov

**2. A member of the institution connects/creates related Project B to Project A, and sets the visibility to private. (This screen capture only shows creating, but is the same with connecting existing private projects)**

https://user-images.githubusercontent.com/49764220/229821015-06f67642-6c07-421b-a987-2fc9ee1e9f48.mov

**3. By clicking on Project B listed under related Projects on Project A, the researcher is able to view contributor-view (?) of Project B (first clip). If this same researcher tries to access the Project from the link, they are not able to (second clip). This is also not in the Project activity on either Project (I think creating related project does not result in any project activity).**

https://user-images.githubusercontent.com/49764220/229821727-ba4d61fd-8724-48dd-a1db-e6050c676a0f.mov

https://user-images.githubusercontent.com/49764220/229822422-0c2237fa-74af-4244-b047-c4713271ce1e.mov

**Comment by birbjam** [comment]
@corrieroe for both of these Projects, is the Project creator the same user?

**Comment by corrieroe** [comment]
@birbjam - No, it is separate users, sorry probably confusing with using the same names, but Project A was created by corrieroe in researcher account, and the private Project B was created by caroe2023 in institution account. I also checked - corrieroe is not a member of the latter institution account.

**Comment by birbjam** [comment]
This is pretty much done, just needs to be tested in the test hub and then moved to the main hub.
