### ISSUE TITLE
Registration content update - time limit

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#821]
New content for "verify your email" page; [doc is here](https://docs.google.com/document/d/144jYH6HYGeNUWR-YMSD469wU6NmHpcp4ryf4T7_2XdE/edit)

<img width="686" alt="Verify your email" src="https://user-images.githubusercontent.com/49764220/232877849-4fdcbacb-1e94-45cb-b6d4-ec6ea7e767bb.png">

### Verify your email
**A verification link has been sent to the email you provided.** 

- Your email must be verified within 30 days in order to be activated.
- If you have verified your email, you are all set! You can close this window.

**Not seeing an email?**
- Check your spam or junk folder for an email from no-reply@localcontextshub.org
- If you do not receive an email within five minutes, please enter your email below to send it again.

**Comment by birbjam** [comment]
![Screenshot 2023-04-20 at 1 25 21 PM](https://user-images.githubusercontent.com/41635757/233479932-5fac5a44-0561-4abf-a609-62ad8cc09d4d.png)
