### ISSUE TITLE
Institution account reg content update - time limit

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#824]
Updated content for preparation step for institution account (different content for community account); [doc](https://docs.google.com/document/d/144jYH6HYGeNUWR-YMSD469wU6NmHpcp4ryf4T7_2XdE/edit)
<img width="687" alt="Preparation step institution" src="https://user-images.githubusercontent.com/49764220/232878276-c47c6ae0-83a7-40cd-a872-52ccfd635739.png">

### Preparation Step
**Things to know before you start creating a new account**

**1. As the creator of this new account, you will become the main administrator by default.** 
You will be the main administrator and the point of contact for the account. If you would like to change the account contact or your role after creating your account, please contact us.

**2. In order to confirm your account, we will ask for the contact information for an institutional representative or a letter outlining their approval.** 
We ask to confirm that the account you are creating has the permission from an appropriate representative of your institution to be active on the platform. Since this account will represent your institution on the Hub, the institutional representative should be someone who has the responsibility for authorizing third-party and/or external agreements on behalf of your organization.

We will ask for the representative’s name and email, or you may upload a signed letter outlining their approval to join the Hub. The contact information or letter are needed in order to create a new account. 

Until the account is confirmed, certain features will not be available. This confirmation must be completed within 90 days, or the account will be suspended. If you have any questions, please contact us. If you are trying out the Hub, please join our [sandbox site](https://anth-ja77-lc-dev-42d5.uc.r.appspot.com/register).

**Comment by birbjam** [comment]
![Screenshot 2023-04-20 at 1 24 26 PM](https://user-images.githubusercontent.com/41635757/233479743-03ee5e01-c9f8-42da-be64-9ad170a775d4.png)
