### ISSUE TITLE
Missing original Label language info on view and edit Label pages

### ISSUE THREAD

**Issue by arojas1** [biocodellc/localcontexts_db#847]
The language for the first or original Label customization is missing from the View Label page, Edit Label page, and when the Label is clicked on in the Labels tab (Select Labels page). Only the extra translations show the languages added Images below:
![image](https://github.com/biocodellc/localcontexts_db/assets/60452620/0b8ce378-bb31-4868-8be0-a3343d9493c3)
![image(1)](https://github.com/biocodellc/localcontexts_db/assets/60452620/8fefa8fb-a5fd-43dc-95a6-2ecc8f5346b3)
![image(2)](https://github.com/biocodellc/localcontexts_db/assets/60452620/404978f6-9bca-4f5f-83b6-dc9be9015c0c)

**Comment by birbjam** [comment]
Ok, I think I hit them all:

![Screenshot 2023-06-02 at 2 31 25 PM](https://github.com/biocodellc/localcontexts_db/assets/41635757/82323ad4-fb4a-4693-8af1-b89ed01df11c)
![Screenshot 2023-06-02 at 2 40 49 PM](https://github.com/biocodellc/localcontexts_db/assets/41635757/3d7f06ae-6d8a-48ac-a823-f49361ec6753)
![Screenshot 2023-06-02 at 2 49 19 PM](https://github.com/biocodellc/localcontexts_db/assets/41635757/d6dda8b2-d9d2-4395-8cf5-a1fd94f12944)
