### ISSUE TITLE
Account settings: Image uploads testing

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#871]
**Researcher account**
- Not showing a preview, but it does upload after hitting save - see video below
- When uploaded, the preview is showing as a rectangle, but is actually a square

https://github.com/biocodellc/localcontexts_db/assets/49764220/69860582-0c86-4b1d-98cb-bdefb11292a1

**Community account**
- had to select the photo twice in order for it to go - this did not happen with other account types (even w same photo). Also tried other photos in community account. See video.

https://github.com/biocodellc/localcontexts_db/assets/49764220/2014fafc-96a3-49f2-9438-8ed25a0d18db

**Comment by birbjam** [comment]
@arojas1 this has been partially fixed, just the community bit needs to be looked at.

**Comment by arojas1** [comment]
- Issue for Community acct on Chrome, not Firefox
- Community acct cannot upload img at all in Safari
- Img upload OK on Safari for Researchers and Institutions, but img preview does not show until after save (Firefox and Chrome OK for both upload and preview)
