### ISSUE TITLE
Adding an institution entity field separate from ROR/non-ROR name

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#896]
With ROR registration page there would be an additional field for the user to add a library, archive, or department name etc. 
Institution entity becomes the ROR institution.

So if ROR institution is New York University, that becomes the entity and the institution name would be Department of Anthropology.

This will help with organizing clusters (#397) and providing specificity to institution account creation.

**Comment by corrieroe** [comment]
Submitted suggested content for this field #910
