### ISSUE TITLE
Community entity helphint language consistency

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#911]
### Currently
Helphint during account selection process:
<img width="400" alt="Screen Shot 2023-08-01 at 10 36 37 AM" src="https://github.com/biocodellc/localcontexts_db/assets/49764220/4a2f95e3-4d1f-4c79-abb3-f4e3d754ff58">

Helphint during community account creation:
<img width="400" alt="Screen Shot 2023-08-01 at 10 36 55 AM" src="https://github.com/biocodellc/localcontexts_db/assets/49764220/ac6266bd-8396-4cdf-8563-a232217c0be1">

### Update
**Where:** Select an account > Community Account helphint
A community entity might be an Indigenous or local community’s Cultural Department; Tribal and Historical Preservation Office; Community Center; Preservation Office; Community Library, Archive, or Museum; Land Council; or Indigenous Rangers.

**Where:** Community creation > Community Entity field helphint
A community entity is responsible for and looks after the development of the community’s Labels. A community entity might be an Indigenous or local community’s Cultural Department; Tribal and Historical Preservation Office; Community Center; Preservation Office; Community Library, Archive, or Museum; Land Council; or Indigenous Rangers.

**Comment by birbjam** [comment]
![Image](https://github.com/biocodellc/localcontexts_db/assets/41635757/176d6856-c296-474a-8e3f-f061d13b6307)



![Image](https://github.com/biocodellc/localcontexts_db/assets/41635757/d716653d-bfe4-4034-8bbd-4f783b8a371d)
