### ISSUE TITLE
Content update for Project visibility

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#912]
**Update language in Project visibility for Project Board, also capitalize Project and clarify content.**

### Currently

<img width="500" alt="Screen Shot 2023-08-01 at 10 36 17 AM" src="https://github.com/biocodellc/localcontexts_db/assets/49764220/87752dce-7c2d-412d-97fd-df73fe86e91b">

<img width="500" alt="Screen Shot 2023-08-01 at 10 36 23 AM" src="https://github.com/biocodellc/localcontexts_db/assets/49764220/1a9c63be-1ec6-4471-95a0-4e5b65d5da44">

### Update
**Create Project > Visibility**

Who can find and view this Project? 

Public: Project contributors and notified communities can interact with the Project. Anyone can access the Project with the Project URL, your page in the registry, or the Projects Board.
Contributor View: Project contributors and notified communities can interact with the Project. Anyone with the Project URL can view the Project ID and Labels/Notices.
Private: Only the Project creator can view the Project. This visibility changes to Contributor View if contributors are added, communities are notified, or Labels applied.

**Create Project > Visibility helphint**
Limited Project information can be accessed with the Hub API:

Public: Project title, ID, and attached Labels/Notices 
Contributor View: Project title and ID
Private: Private Projects cannot be accessed with the Hub API

To learn more, see the [Hub API Guide](https://localcontexts.org/support/api-guide/).

**Comment by birbjam** [comment]
![Screenshot 2023-08-08 at 3 22 26 PM](https://github.com/biocodellc/localcontexts_db/assets/41635757/29f914bb-f940-4920-bad7-ddb3a5ab1656)
![Screenshot 2023-08-08 at 3 29 05 PM](https://github.com/biocodellc/localcontexts_db/assets/41635757/08d93181-8dd5-48ca-9224-0bb1fe4e71d6)
