### ISSUE TITLE
Content for Project Board description

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#913]
**Description for new Projects Board page. I think keep simple for now.**

This Project Board shows all public Projects created on the Local Contexts Hub. View a Project to see additional details.

**Comment by birbjam** [comment]
Also removing Visibility column from this table.

**Comment by birbjam** [comment]
![Image](https://github.com/biocodellc/localcontexts_db/assets/41635757/a3a45396-b067-4cbb-b75a-e3ec6710ca1f)
