### ISSUE TITLE
Project comments, activity - helphints

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#914]
**To make clear that Project comments and activity are not visible, even on public projects.** I'm removing the Privacy Policy info in our comments helphint - will need to check if this is okay legally, I think UI/UX-wise it is awkward/unnecessary.

### Currently
<img width="700" alt="Screen Shot 2023-08-01 at 12 58 32 PM" src="https://github.com/biocodellc/localcontexts_db/assets/49764220/9d5f541c-7010-4b6e-9b37-b9720f1498c0">

### Update

**Project action page > Project comments helphint adjustment**
A place to discuss the Project with other contributors. Project comments are only visible to Project contributors.

**Project action page > Project activity - add helphint**
Project activity is only visible to Project contributors.

**Comment by birbjam** [comment]
![Image](https://github.com/biocodellc/localcontexts_db/assets/41635757/9f31929d-30ba-4aa2-94ad-4d6a77ddd1bb)

**Comment by birbjam** [comment]
![Image](https://github.com/biocodellc/localcontexts_db/assets/41635757/86deb954-733e-4b73-9f91-4a22896a84d8)
